export const HOME_RECIPE_CATEGORIES = [
  "Vegetarian",
  "Lunch",
  "Dinner",
  "Breakfast",
  "Italian",
] as const;

export const FALLBACK_RECIPE_CATEGORIES = [
  "Vegetarian",
  "Lunch",
  "Dinner",
  "Breakfast",
  "Italian",
  "Salads",
  "Soups",
  "Chicken",
  "Pasta",
  "Desserts",
  "Drinks",
  "Healthy",
  "Quick Meals",
  "Indian",
  "Mexican",
  "Asian",
] as const;

export const MANAGED_RECIPE_CATEGORIES = [
  "Vegetarian",
  "Lunch",
  "Dinner",
  "Breakfast",
  "Italian",
  "Salads",
  "Soups",
  "Chicken",
  "Pasta",
  "Desserts",
  "Drinks",
  "Healthy",
  "Quick Meals",
  "Indian",
  "Mexican",
  "Asian",
  "Seafood",
  "BBQ",
  "Japanese",
  "Korean",
  "Chinese",
  "Smoothies",
  "Vegan",
  "Other",
] as const;

export type HomeRecipeCategory = (typeof HOME_RECIPE_CATEGORIES)[number];
export type FallbackRecipeCategory = (typeof FALLBACK_RECIPE_CATEGORIES)[number];
export type ManagedRecipeCategory = (typeof MANAGED_RECIPE_CATEGORIES)[number];

export const RECIPE_CATEGORY_ICONS: Record<string, any> = {
  Vegetarian: "leaf",
  Lunch: "silverware-fork-knife",
  Dinner: "silverware",
  Breakfast: "coffee",
  Italian: "pizza",
  Salads: "food-variant",
  Soups: "bowl-mix-outline",
  Chicken: "food-drumstick-outline",
  Pasta: "noodles",
  Desserts: "cake-variant-outline",
  Drinks: "cup",
  Healthy: "heart-pulse",
  "Quick Meals": "timer-sand",
  Indian: "pot-steam",
  Mexican: "taco",
  Asian: "rice",
  Seafood: "fish",
  BBQ: "grill",
  Japanese: "bowl-mix-outline",
  Korean: "bowl-mix",
  Chinese: "food",
  Smoothies: "cup",
  Vegan: "sprout",
  Other: "food",
};
